env.data: local

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dev-example
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    #open-in-view: false
  output:
    ansi:
      enabled: always
logging.level:
  org.hibernate.SQL: debug
  com.example.devexample.dev: trace